name: Сборка проекта CMake и запуск Юнит-тестов

on:
  pull_request:
    branches:
      - main_branch  # Основная ветка выполнения

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: КЛОНИРОВАНИЕ РЕПОЗИТОРИЯ НА ВИРТУАЛЬНУЮ МАШИНУ ДЛЯ ИСПОЛНЕНИЯ...
      uses: actions/checkout@v2

    - name: УСТАНОВКА "CMake"...
      uses: jwlawson/actions-setup-cmake@v1

    - name: СОЗДАЕМ ПАПКУ build...
      run: |
        if [ ! -d "build" ]; then
          mkdir build  
        fi

    - name: ГЕНЕРАЦИЯ ФАЙЛОВ СБОРКИ С ПОМОЩЬЮ CMAKE...
      run: cmake -S . -B build

    - name: СБОРКА ПРОЕКТА...
      run: cmake --build build -- -j

    - name: ЗАПУСК ЮНИТ-ТЕСТОВ...
      run: |
        cd build/tests
        ./my_tests
