name: CMake Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: СОЗДАЕМ ПАПКУ build...
      run: |
        if [ ! -d "build" ]; then
          mkdir build  
        fi

    - name: ГЕНЕРАЦИЯ ФАЙЛОВ СБОРКИ С ПОМОЩЬЮ CMAKE...
      run: cmake -S . -B build

    - name: СБОРКА ПРОЕКТА...
      run: cmake --build build -- -j

    - name: ЗАПУСК ЮНИТ-ТЕСТОВ...
      run: |
        cd build/tests
        ./my_tests 
