name: Сборка проекта CMake и запуск Юнит-тестов

on:
  pull_request:
    branches:
      - main  # Основная ветка выполнения

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: КЛОНИРОВАНИЕ РЕПОЗИТОРИЯ НА ВИРТУАЛЬНУЮ МАШИНУ ДЛЯ ИСПОЛНЕНИЯ...
      uses: actions/checkout@v2

    - name: УСТАНОВКА "CMake"...
      uses: jwlawson/actions-setup-cmake@v1

    - name: СОЗДАЕМ ПАПКУ build...
      run: |
        if [ ! -d "build" ]; then
          mkdir build  
        fi

    - name: ГЕНЕРАЦИЯ ФАЙЛОВ СБОРКИ С ПОМОЩЬЮ CMAKE...
      run: cmake -S . -B build

    - name: СБОРКА ПРОЕКТА...
      run: cmake --build build -- -j

    - name: ЗАПУСК ЮНИТ-ТЕСТОВ...
      run: |
        cd build/tests
        ./my_tests
      continue-on-error: true  # Чтобы сборка не останавливалась при неуспешных тестах

    - name: СООБЩЕНИЕ О РЕЗУЛЬТАТАХ
      run: |
        if [ $? -ne 0 ]; then
          echo "Тесты не прошли, слияние отменяется."
          exit 1
        else
          echo "Тесты прошли успешно, слияние продолжается."
      id: test_results

    - name: СЛИЯНИЕ ВЕТКИ test_merge В main
      if: ${{ steps.test_results.outcome == 'success' }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout main
        git merge test_merge
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
